### ISSUE TITLE
Only string keys?

### ISSUE THREAD

**Issue by UnixJunkie** [dinosaure/art#15]
Hello,

So any type of values are supported but only string keys?

Maybe also proposing an interface with 'a keys (that you internally marshal
to string) might be useful.

If your persistent module can really be used by multi process programs
to exchange values (one writer, several readers); this could be quite useful
for parallel programming. Currently I use UDP sockets in my parany
library, but your stuff could be even better.

Regards,
F.

**Comment by UnixJunkie** [comment]
For inspiration maybe:
https://github.com/UnixJunkie/dokeysto/blob/master/src/db_gen.ml

In your case, you just need string_of_key and key_of_string
in your parameterizing module.
You can provide a default converting module using Marshal.{to_string|from_string}.

**Comment by dinosaure** [comment]
Hi, I'm not really sure about such proposal when the given string as a key must do not contain any `\000` - which has a signification internally. I don't really know `Marshal` in details so I'm not sure if it respects this predicate.

Then, if the end-user would like to use something else than a `string`, he can provide its own serializer/deserializer function with the mind of `Art.key` - and be responsible about bugs if they exist (as I said, if the serializer/deserializer produces a `\000`).

**Comment by UnixJunkie** [comment]
I see. Maybe there is another problem too: the conversion to/from string must preserve the ordering of keys.
It's ok, don't bother about my remark then.
